name: 🦜🔍 Aviary Testing

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[backend, test, frontend]"
      - name: Run the backend
        run: |
          uvicorn tests.mock_app:app &
          sleep 5
      - name: Test with pytest
        env:
          AVIARY_TOKEN: ${{ secrets.AVIARY_TOKEN }}
          AVIARY_URL: http://0.0.0.0:8000/
        run: |
          pytest tests/test_*
